export const quotes = [
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.", author: "Albert Einstein" },
    { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
    { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
    { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
    { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
    { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
    { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
    { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { text: "Science without religion is lame, religion without science is blind.", author: "Albert Einstein" },
    { text: "The difference between genius and stupidity is that genius has its limits.", author: "Albert Einstein" },
    { text: "You can't blame gravity for falling in love.", author: "Albert Einstein" },
    { text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein" },
    { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
    { text: "Everything should be made as simple as possible, but not simpler.", author: "Albert Einstein" },
    { text: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
    { text: "You have to learn the rules of the game. And then you have to play better than anyone else.", author: "Albert Einstein" },
    { text: "I never think of the future. It comes soon enough.", author: "Albert Einstein" },
    { text: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
    { text: "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.", author: "Albert Einstein" },
    { text: "The best way to predict the future is to invent it.", author: "Albert Einstein" },
    { text: "Insanity: doing the exact same thing over and over again and expecting different results.", author: "Albert Einstein" },
    { text: "The most incomprehensible thing about the world is that it is comprehensible.", author: "Albert Einstein" },
    { text: "We should take care not to make the intellect our god; it has, of course, powerful muscles, but no personality.", author: "Albert Einstein" },
    { text: "No problem can be solved from the same level of consciousness that created it.", author: "Albert Einstein" },
    { text: "The greatest scientists are artists as well.", author: "Albert Einstein" },
    { text: "I am not a genius. I am just passionately curious.", author: "Albert Einstein" },
    { text: "To be a success, be open to change and to the ways of new discoveries.", author: "Albert Einstein" },
    { text: "The universe is not only stranger than we imagine, it is stranger than we can imagine.", author: "Albert Einstein" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "The difference between stupidity and genius is that genius has its limits.", author: "Albert Einstein" },
    { text: "Science is a wonderful thing if one does not have to earn one's living at it.", author: "Albert Einstein" },
    { text: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein" },
    { text: "To punish me for my contempt for authority, fate made me an authority myself.", author: "Albert Einstein" },
    { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein" },
    { text: "In order to form an immaculate member of a flock of sheep one must, above all, be a sheep.", author: "Albert Einstein" },
    { text: "Everything that is really great and inspiring is created by the individual who can labor in freedom.", author: "Albert Einstein" },
    { text: "The only real valuable thing is intuition.", author: "Albert Einstein" },
    { text: "I am by heritage a Jew, by citizenship a Swiss, and by education a German. The seven years I spent in the United States as a professor and a researcher have left an indelible mark on my career.", author: "Albert Einstein" },
    { text: "The hardest thing in the world to understand is the income tax.", author: "Albert Einstein" },
    { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
    { text: "The eternal mystery of the world is its comprehensibility.", author: "Albert Einstein" },
    { text: "All that is valuable in human society depends upon the opportunity for development accorded the individual.", author: "Albert Einstein" },
    { text: "A man should look for what is, and not for what he thinks should be.", author: "Albert Einstein" },
    { text: "Everything that can be counted does not necessarily count; everything that counts cannot necessarily be counted.", author: "Albert Einstein" },
    { text: "The most beautiful experience we can have is the mysterious.", author: "Albert Einstein" },
    { text: "You do not really understand something unless you can explain it to your grandmother.", author: "Albert Einstein" },
    { text: "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.", author: "Albert Einstein" },
    { text: "The measure of a man is what he does with power.", author: "Albert Einstein" },
    { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Albert Einstein" },
    { text: "Do not worry about your difficulties in Mathematics. I can assure you mine are still greater.", author: "Albert Einstein" },
    { text: "It is the theory which decides what we can observe.", author: "Albert Einstein" },
    { text: "You cannot simultaneously prevent and prepare for war.", author: "Albert Einstein" },
    { text: "The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.", author: "Albert Einstein" },
    { text: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
    { text: "The only real valuable thing is intuition.", author: "Albert Einstein" },
    { text: "If we knew what it was we were doing, it would not be called research, would it?", author: "Albert Einstein" },
    { text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein" },
    { text: "Great ideas come from the subconscious, but only if we give them the freedom to surface.", author: "Albert Einstein" },
    { text: "We can't solve problems by using the same kind of thinking we used when we created them.", author: "Albert Einstein" },
    { text: "The whole of science is nothing more than a refinement of everyday thinking.", author: "Albert Einstein" },
    { text: "Every child is born a genius.", author: "Albert Einstein" },
    { text: "There is no place for the state in the realm of science and literature.", author: "Albert Einstein" },
    { text: "The best way to cheer yourself up is to try to cheer somebody else up.", author: "Albert Einstein" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The measure of a man's real character is what he would do if he knew he would never be found out.", author: "Albert Einstein" },
    { text: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
    { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Albert Einstein" }
];
